# vim: set ft=ruby :
Vagrant::Config.run do |config|

  config.vm.define :master do |master_config|
    master_config.vm.box = "master"
    master_config.vm.box_url = "https://s3-sa-east-1.amazonaws.com/willian-boxes/UbuntuServer12.04amd64.box"
    master_config.vm.network :hostonly, "192.168.12.12"
    
    master_config.vm.provision :shell, :inline => "apt-get -y update"
    master_config.vm.provision :shell, :inline => "apt-get -y install git debhelper debconf build-essential inotify-tools msmtp"
    master_config.vm.provision :shell do |shell|
      shell.path = "getbabs.sh"
    end
  end

  config.vm.define :slave1 do |slave1_config|
    slave1_config.vm.box = "slave1"
    slave1_config.vm.box_url = "https://s3-sa-east-1.amazonaws.com/willian-boxes/UbuntuServer12.04amd64.box"
    slave1_config.vm.network :hostonly, "192.168.12.50"
  end

  config.vm.define :slave2 do |slave2_config|
    slave2_config.vm.box = "slave2"
    slave2_config.vm.box_url = "https://s3-sa-east-1.amazonaws.com/willian-boxes/UbuntuServer12.04amd64.box"
    slave2_config.vm.network :hostonly, "192.168.12.51"
    slave2_config.vm.provision :shell, :inline => "dpkg -i /vagrant/babs*.deb"
  end
end
