#!/bin/bash
#
# C672 build
#
export WORKROOT=${AUTOBUILDER_WORKROOT}
checkout_path=${AUTOBUILDER_MODULES_FILE%/modules}
checkout_path=${checkout_path#*Products/}

# First we want to check out the sandbox
echo ${checkout_path}
( cd $WORKROOT && getstable -repository s-and-s -w -r $AUTOBUILDER_REVISION ${checkout_path} &> $AUTOBUILDER_CHECKOUT_LOGFILE ) || die "$REPORT_ERR_CHECKOUT_FAILED"

# Now we want to run the build
( cd "$AUTOBUILDER_BUILDSYS_PATH" && export WORKROOT=$WORKROOT; make "$AUTOBUILDER_BUILD_TARGET" &> $AUTOBUILDER_BUILD_LOGFILE ) || die "$REPORT_ERR_BUILD_FAILED"

# Success!
report_generate "Build succeeded"
