#!/bin/bash
#
# C672_reference build
#
report() { report_generate "$WORKROOT" "$WORKROOT/Products/B930/reference/C672_reference/modules" C672_reference_stable "$START_TIME" "$(date)" $@; }

die() {
   report $@
   exit 1
}

export WORKROOT=${AUTOBUILDER_WORKROOT}/C672_reference/build-${AUTOBUILDER_REVISION}-$(date +%H-%M-%S_%d.%m.%Y)
START_TIME=$(date)

# Create the build directory
test -d "$WORKROOT" && die $REPORT_ERR_WORKROOT_EXISTS
mkdir -p "$WORKROOT" || die $REPORT_ERR_CANNOT_CREATE_WORKROOT

# First we want to check out the sandbox
( cd $WORKROOT && getstable -repository s-and-s -w -r $AUTOBUILDER_REVISION B930/reference/C672_reference > $WORKROOT/checkout-log.txt 2>&1 ) || die $REPORT_ERR_CHECKOUT_FAILED

# Now we want to run the build
( cd $WORKROOT/buildsys/C672_reference && export WORKROOT=$WORKROOT; make testbuild > $WORKROOT/testbuild-log.txt 2>&1 ) || die $REPORT_ERR_BUILD_FAILED
report "Build succeeded"
