#!/bin/bash
#
# Dimiter build
#
report() { report_generate "$WORKROOT" "$WORKROOT/Products/B930/reference/dimiter/modules" B930_dimiter_stable "$START_TIME" "$(date)" $@; }

die() {
   report $@
   exit 1
}

export WORKROOT=${AUTOBUILDER_WORKROOT}/D183/build-${AUTOBUILDER_REVISION}-$(date +%H-%M-%S_%d.%m.%Y)
START_TIME=$(date)

# Create the build directory
test -d "$WORKROOT" && die $REPORT_ERR_WORKROOT_EXISTS
mkdir -p "$WORKROOT" || die $REPORT_ERR_CANNOT_CREATE_WORKROOT

# First we want to check out the sandbox
( cd $WORKROOT && getstable -repository s-and-s -w -r $AUTOBUILDER_REVISION B930/reference/dimiter > $WORKROOT/checkout-log.txt 2>&1 ) || die $REPORT_ERR_CHECKOUT_FAILED

# Now we want to run the build
( cd $WORKROOT/buildsys/B868-cora && export WORKROOT=$WORKROOT; make testbuild > $WORKROOT/testbuild-log.txt 2>&1 ) || die $REPORT_ERR_BUILD_FAILED
report "Build succeeded"
