#!/bin/bash
#
# An example babs build script
#
# This script only really needs to worry about the build process for your
# project.  The finer details of interacting with the babs job runner can be
# largely left up to babs.  This said, babs will provide certain helper
# functions and environmental variables which may help.
#
# Environmental variables:
#
#     BABS_BUILD_TITLE
#     	This is the title of the babs build as defined in babs.ini
#
#     BABS_BRANCH_NAME
#     	This is the branch name of the babs build as defined in babs.ini
#
#     BABS_REVISION
#       This is the SCM revision your script should build
#
#     BABS_BUILD_TARGET
#       This is the babs build target as defined in babs.ini
#
#     BABS_WORKROOT
#       This is the build directory babs autogenerates for you to check out
#       and build your project in.  babs will cd your script into this
#       directory before it is executed.
#
#     BABS_CHECKOUT_LOGFILE
#       This is the path of an autogenerated file for you to log your
#       build's checkout from SCM.  It is optional whether you use this or
#       not.
#
#     BABS_BUILD_LOGFILE
#       This is the path of an autogenerated file for you to log your
#       build's compilation process.  It is optional whether you use this
#       or not.
#
#     BABS_START_TIME
#       This variable records the time your build was started.  It is used in
#       report generation by the babs helper functions.
#
# Helper functions:
#
#     report_generate()
#        This function takes a string describing the build status as $1, and
#        generates a standard babs build report.
#
#     die()
#        This function takes a string describing the build status as $1, and
#        calls report_generate() before exiting with an error code.
#
